name: release

on:
  push:
    branches: 
      - master

jobs:
  release-baseci:
    name: Release baseci

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2

    - name: Login to docker hub
      run: docker login --username gravitysketch --password ${{ secrets.HUB_TOKEN }}

    - name: Build baseci image
      run: |
        docker pull gravitysketch/baseci:latest || true
        docker build \
          --pull \
          --cache-from gravitysketch/baseci:latest \
          -t gravitysketch/baseci:latest \
          -f ./baseci/Dockerfile \
          ./baseci
    
    - name: Release baseci image
      run: |
        docker push \
          gravitysketch/baseci:latest

    - name: Logout of docker hub
      if: always()
      run: docker logout